.TH Dump-join 


.SH NAME
dump-join - a support tool for airgraph-ng that allows you to join the airodump output files.

.SH SYNOPSIS
dump-join.py -i foo_name_1 foo_name_2 foo_name_3 .... -o output-file.txt

.SH DESCRIPTION
A simple support tool that allows joining of airodump files into one 
larger file. It supports an unlimited amount of input files to a 
single output file.

.SH OPTIONS
.IP -i 
Input Files [ foo_name_1 foo_name_2 foo_name_3 ..]
.IP -o      
Output File

 

