.TH IVSTOOLS 1 "April 2015" "Version 1.2-rc2"

.SH NAME
ivstools - extract IVs from a pcap file or merges several .ivs files into one
.SH SYNOPSIS
.B ivstools
--convert <pcap file> <ivs output file>
.B ivstools
--merge <ivs file 1> <ivs file 2> .. <output file>
.SH DESCRIPTION
.BI ivstools
is a tool designed to extract ivs (initialization vectors) from a pcap dump to an ivs file and it can also merge several ivs (initialization vectors) files into one..
.SH EXAMPLE
.B ivstools
--convert wep_dump.cap out.ivs
.B ivstools
--merge myivs1.ivs myivs2.ivs myivs3.ivs allivs.ivs
.SH AUTHOR
This manual page was written by Adam Cecile <gandalf@le-vert.net> for the Debian system (but may be used by others).
Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 2 or any later version published by the Free Software Foundation
On Debian systems, the complete text of the GNU General Public License can be found in /usr/share/common-licenses/GPL.
.SH SEE ALSO
.br
.B airbase-ng(8)
.br
.B aireplay-ng(8)
.br
.B airmon-ng(8)
.br
.B airodump-ng(8)
.br
.B airodump-ng-oui-update(8)
.br
.B airserv-ng(8)
.br
.B airtun-ng(8)
.br
.B besside-ng(8)
.br
.B easside-ng(8)
.br
.B tkiptun-ng(8)
.br
.B wesside-ng(8)
.br
.B aircrack-ng(1)
.br
.B airdecap-ng(1)
.br
.B airdecloak-ng(1)
.br
.B airolib-ng(1)
.br
.B besside-ng-crawler(1)
.br
.B buddy-ng(1)
.br
.B kstats(1)
.br
.B makeivs-ng(1)
.br
.B packetforge-ng(1)
.br
.B wpaclean(1)
