.TH AIROSCONF 1 "May  4, 2008"

.SH NAME
airosconf - update airoscript and airosperl config

.SH DESCRIPTION
airosconf is a tool designed for automating update/editing of airoscript and
airosperl config files.

.br.

.SH SYNOPSIS
.B airosconf 
[options]

.SH OPTIONS
.TP
--set
  --to-airoscript
  --to-airosperl

--update
  --from-airoscript
  --from-airosperl

.SH AUTHOR
Airosconf was written by David Francos Cuartero (XayOn) <yo.orco@gmail.com>.
.br
This manual page was written by David Francos Cuartero (XayOn) <yo.orco@gmail.com>.

.SH SEE ALSO
.br
.B airdecap-ng(1)
.br
.B airdriver-ng(1)
.br
.B aireplay-ng(1)
.br
.B airmon-ng(1)
.br
.B airodump-ng(1)
.br
.B airolib-ng(1)
.br
.B airsev-ng(1)
.br
.B airtun-ng(1)
.br
.B buddy-ng(1)
.br
.B easside-ng(1)
.br
.B ivstools(1)
.br
.B kstats(1)
.br
.B makeivs-ng(1)
.br
.B packetforge-ng(1)
.br
.B wesside-ng(1)
.br
.B aircrack-ng(1)
