#!/bin/bash
# Unstable functions file for airoscript.
# Requires: wlandecrypter 

# Copyright (C) 2009, 2010 David Francos Cuartero
#        This program is free software; you can redistribute it and/or
#        modify it under the terms of the GNU General Public License
#        as published by the Free Software Foundation; either version 2
#        of the License, or (at your option) any later version.

#        This program is distributed in the hope that it will be useful,
#        but WITHOUT ANY WARRANTY; without even the implied warranty of
#        MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#        GNU General Public License for more details.

#        You should have received a copy of the GNU General Public License
#        along with this program; if not, write to the Free Software
#        Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

doitwld(){
    echo "Cracking WLAN"; sleep 2
	execute $WLD $Host_SSID $Host_SSID $DUMP_PATH/wlddic 
	execute $AIRCRACK -b $Host_SSID -w $DUMP_PATH/wlddic $DUMP_PATH/$Host_SSID-01.cap
}

doitjt(){
    echo "Cracking Jazztel"; sleep 2
	execute $JTD $Host_SSID $Host_SSID $DUMP_PATH/jtddic
	execute $AIRCRACK  -b $Host_SSID -w $DUMP_PATH/jtddic $DUMP_PATH/$Host_SSID-01.cap
}

wld(){
    echo "WLAN"
    if [ "$Host_SSID" == "" ]; then clear; echo -e "gettext `'Error: You must select a client before performing this attack'`\n"; fi
    if [[ "$Host_SSID" =~ WLAN* ]]; then
        if [ -e $DUMP_PATH/$Host_MAC-01.cap ]; then doitjtd
        else echo "`gettext 'No capture file. Capture some ivs'`"; fi
    else
        _ "Cant crack this network with this dictionary $Host_SSID"
    fi
}

jtd(){
    echo "JAZZTEL"
    if [ "$Host_SSID" == "" ]; then clear; echo -e "gettext `'Error: You must select a client before performing this attack'`\n"; fi
    if [[ "$Host_SSID" =~ JAZZTEL* ]]; then
        if [ -e $DUMP_PATH/$Host_MAC-01.cap ]; then doitjtd
        else echo "`gettext 'No capture file. Capture some ivs'`"; fi
    else
        _ "Cant crack this network with this dictionary"
    fi
}

auto(){
    $AIROSCWORDLIST $DUMP_PATH/$Host_SSID.dic $CMPFILE $Host_SSID $Host_SSID;
    if [ $? =! "404" ]; then $AIRCRACK -f $DUMP_PATH/$Host_SSID.key -b $Host_SSID -w $DUMP_PATH/$Host_SSID.dic $DUMP_PATH/$Host_SSID*.cap; fi
        if [ $? == "404" ]; then crack; fi
}
