#!/bin/bash
# Unstable functions file for airoscript.
# Requires: wlandecrypter 

# Copyright (C) 2009, 2010 David Francos Cuartero
#        This program is free software; you can redistribute it and/or
#        modify it under the terms of the GNU General Public License
#        as published by the Free Software Foundation; either version 2
#        of the License, or (at your option) any later version.

#        This program is distributed in the hope that it will be useful,
#        but WITHOUT ANY WARRANTY; without even the implied warranty of
#        MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#        GNU General Public License for more details.

#        You should have received a copy of the GNU General Public License
#        along with this program; if not, write to the Free Software
#        Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

digenpy(){
    if [ "$3" == "crack" ]; then
        execute "Cracking" crack $AIRCRACK -0 -l $DUMP_PATH/$Host_MAC.key -w $DUMP_PATH/digenpy_dic $DUMP_PATH/$Host_MAC-01.cap
    else AUTO=1; QUIET=1;
        execute "Creating dictionary ($1:$2) for $Host_SSID" digenpy $1 $2 $Host_MAC $Host_SSID > $DUMP_PATH/digenpy_dic
    AUTO=0; QUIET=""; fi
}

Telefonica(){ if [[ "$Host_SSID" =~ WLAN* ]]; then digenpy Spain Telefonica crack; cracked=1;  fi }
Jazztel(){ if [[ "$Host_SSID" =~ JAZZTEL* ]]; then digenpy Spain Jazztel crack; cracked=1;  fi; }

auto(){
    if [ "$Host_SSID" == "" ]; then clear; echo -e "`gettext 'Error: You must select a target first'`\n"; return; fi
    if [ -e "$DUMP_PATH/$Host_MAC-01.cap" ]; then 
        for function in $_functions; do $function; [[ "$cracked" == "1" ]] && return; done
    else echo "`gettext 'Error: No capture file. Capture some ivs'`"; fi

    _ "Cant crack this network like this, do it manually"
    selectcracking
}
