#!/bin/bash
function _powerline() { export PS1="$(~/.jabashit/powerline/powerline-bash.py $?)"; }

[[ $jabashit_use_powerline ]] && {
   export PROMPT_COMMAND="_powerline"
} || {
    debchroot='${debian_chroot:+($debian_chroot)}'
    userhost='\[\033[01;32m\]\u@\h\[\033[00m\]:'
    workingdir='\[\033[01;34m\]\w\[\033[00m\]\$ '
}

