.TH AIROSCRIPT 1 "August 3, 2011"

.SH NAME
airoscript - text interface to aircrack-ng

.SH DESCRIPTION
airoscript is program designed to ease the use of aircrack-ng. 
.br .
airoscript allows you to scan select and attack any detected access poing and guides you trought different kinds of attacks available for selected ap's encryption type.

.SH SYNOPSIS
.B airoscript [-h] [-t TERMINAL] [-s] [-v] [-m] [-b] [-c] [-x] [-n FILTER] [-w WIFICARD] [-f] [-a]

.TP
.I -t TERMINAL 
Especifies the terminal to use instead of the one in config file.
.PP

.TP
.I -s
Uses screen interface instead of xterm (unstable)
.PP

.TP
.I -v
Enables verbose and debug mode
.PP

.TP 
.I -d
Writes a csv file with network data

.TP
.I -w [WIFICARD]
Specify wificard (has no effect if no -m -c or -f provided)
.PP

.TP
.I -f
Change mac to fake mac, then start monitor mode
.PP

.TP
.I -c
Use your real mac and start monitor mode
.PP

.TP
.I -m
Start monitor mode without caring about the mac
.PP

.TP
.I -a
Enable automatic mode, starts a completly automatic (non-interactive)
version of airoscript
.BR
If no filter provided, it'll attack all networks (WARN: this might be risky
.PP

.TP
.I -n [REGEX]
Filter essid by REGEX
.PP

.TP
.I -x
Autoconfigure network after automatic crack (requires -a)
.PP

.TP
.I -z
Dont do autoscan at start
.PP

.SH CONFIGURATION
Configuration is done by file /etc/airoscript.conf . 
.br
It should run fine without customization, 
but you can especify terminal and interface
there.
.br

.SH AUTHOR
Airoscript was written by daouid and mantained by David Francos Cuartero.
.br
This manual page was written by David Francos Cuartero <xayon@xayon.net>.

.SH SEE ALSO
.br
.B airoscript.conf(1)
.br
.B airdecap-ng(1)
.br
.B airdriver-ng(1)
.br
.B aireplay-ng(1)
.br
.B airmon-ng(1)
.br
.B airodump-ng(1)
.br
.B airolib-ng(1)
.br
.B airsev-ng(1)
.br
.B airtun-ng(1)
.br
.B buddy-ng(1)
.br
.B easside-ng(1)
.br
.B ivstools(1)
.br
.B kstats(1)
.br
.B makeivs-ng(1)
.br
.B packetforge-ng(1)
.br
.B wesside-ng(1)
.br
.B aircrack-ng(1)
