.TH AIROSCRIPT 1 "December  15, 2008"

.SH NAME
airoscript - console interface to aircrack-ng

.SH DESCRIPTION
airoscript is program designed to ease the use of aircrack-ng. 
.br.
airoscript allows you to scan select and attack any detected access poing and guides you trought different kinds of attacks available for selected ap's encryption type.


.SH SYNOPSIS
.B airoscript
[options]

.SH OPTIONS
.TP
.I TERMINAL 
Especifies the terminal to use instead of the one in config file.

.SH CONFIGURATION
Configuration is done by file /etc/airoscript.conf . 
.br
It should run fine without customization, 
but you can especify resolution, terminal and interface
there.
.br
export reson=1
.br
export resonset="resolution number (1-8)"
.br
TERMINAL="xterm"
.br

.SH AUTHOR
Airoscript was written by daouid and mantained by David Francos Cuartero.
.br
This manual page was written by David Francos Cuartero <yo.orco@gmail.com>.

.SH SEE ALSO
.br
.B airdecap-ng(1)
.br
.B airdriver-ng(1)
.br
.B aireplay-ng(1)
.br
.B airmon-ng(1)
.br
.B airodump-ng(1)
.br
.B airolib-ng(1)
.br
.B airsev-ng(1)
.br
.B airtun-ng(1)
.br
.B buddy-ng(1)
.br
.B easside-ng(1)
.br
.B ivstools(1)
.br
.B kstats(1)
.br
.B makeivs-ng(1)
.br
.B packetforge-ng(1)
.br
.B wesside-ng(1)
.br
.B aircrack-ng(1)
