name: Linux CI

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  push:
    branches: [ master ]
    paths-ignore:
      - apparmor/**
      - contrib/**
      - manpages/**
      - patches/**
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/workflows/alpine.yml'
      - '.github/workflows/coverity.yml'
      - '.github/workflows/docker.yml'
      - '.github/workflows/docker-release.yml'
      - '.github/workflows/linux-pcre.yml'
      - '.github/workflows/macos.yml'
      - '.github/workflows/pvs-studio.yml'
      - '.github/workflows/style.yml'
      - '.github/workflows/windows.yml'
      - '.vscode/**'
      - '.clang-format'
      - '.editorconfig'
      - '.gitignore'
      - '.pre-commit-config.yaml'
      - 'AC_VERSION.in'
      - 'AUTHORS'
      - 'centos_autotools.sh'
      - 'ChangeLog'
      - 'docker_package_install.sh'
      - 'Dockerfile'
      - 'Dockerfile.release'
      - 'INSTALLING'
      - 'LICENSE'
      - 'LICENSE.OpenSSL'
      - 'README'
      - 'README.md'
      - 'SECURITY.md'

  pull_request:
    branches: [ master ]
    paths-ignore:
      - apparmor/**
      - contrib/**
      - manpages/**
      - patches/**
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/workflows/coverity.yml'
      - '.github/workflows/docker.yml'
      - '.github/workflows/docker-release.yml'
      - '.github/workflows/linux-pcre.yml'
      - '.github/workflows/macos.yml'
      - '.github/workflows/pvs-studio.yml'
      - '.github/workflows/style.yml'
      - '.github/workflows/windows.yml'
      - '.vscode/**'
      - '.clang-format'
      - '.editorconfig'
      - '.gitignore'
      - '.pre-commit-config.yaml'
      - 'AC_VERSION.in'
      - 'AUTHORS'
      - 'centos_autotools.sh'
      - 'ChangeLog'
      - 'docker_package_install.sh'
      - 'Dockerfile'
      - 'Dockerfile.release'
      - 'INSTALLING'
      - 'LICENSE'
      - 'LICENSE.OpenSSL'
      - 'README'
      - 'README.md'
      - 'SECURITY.md'

env:
  LANG: en_US.UTF-8
  TZ: UTC

jobs:
  ubuntu_22_04:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        compiler:
          - cc:  gcc-10
            cxx: g++-10
          - cc:  gcc-9
            cxx: g++-9
          - cc:  clang-11
            cxx: clang++-11
        flags:
          - name: Gcrypt
            flags: "--with-gcrypt"
          - name: OpenSSL
            flags: ""

    name: Ubuntu 22.04 ${{ matrix.compiler.cc }} using ${{ matrix.flags.name }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 750
          submodules: 'recursive'

      - uses: actions/cache@v2
        id: cache
        if: ${{ env.ACT != 'true' }}
        with:
          path: |
            /home/runner/.ccache
          key: ${{ runner.os }}-${{ matrix.compiler.cc }}-${{ matrix.flags.name }}-${{ hashFiles('.github/workflows/linux.yml') }}
          restore-keys: ${{ runner.os }}-${{ matrix.compiler.cc }}-${{ matrix.flags.name }}

      - name: Install dependencies
        run: |
          SUDO="$([ "$ACT" = "true" ] || echo sudo)"
          $SUDO apt update -q
          $SUDO apt-get install -y git ${{ matrix.compiler.cc }} ${{ matrix.compiler.cxx }} autoconf automake build-essential ccache ethtool expect hostapd iw lcov libcmocka-dev libgcrypt20-dev libhwloc-dev libnl-3-dev libnl-genl-3-dev libpcap-dev libpcre2-dev libsqlite3-dev libssl-dev libtool pkg-config rfkill screen shtool tcpdump usbutils wpasupplicant zlib1g-dev

      - name: Ccache stats before builds
        run: |
          ccache -s

      - name: Build with ${{ matrix.compiler.cc }} using ${{ matrix.flags.name }}
        env:
          AM_COLOR_TESTS: always
        run: |
          CPUS=$(nproc)
          case "${{ matrix.compiler.cc }}" in
            clang-12)
              CC=clang-11
              CXX=clang++-11
              export CFLAGS="-Werror -Wno-zero-length-array -Wno-deprecated-declarations"
              export CXXFLAGS="-Werror -Wno-zero-length-array -Wno-deprecated-declarations"
              ;;
            clang-11)
              CC=clang-11
              CXX=clang++-11
              export CFLAGS="-Werror -Wno-zero-length-array -Wno-deprecated-declarations"
              export CXXFLAGS="-Werror -Wno-zero-length-array -Wno-deprecated-declarations"
              ;;
            *)
              CC=${{ matrix.compiler.cc }}
              CXX=${{ matrix.compiler.cxx }}
              export CFLAGS="-Werror -Wno-unused-result -Wno-deprecated-declarations"
              export CXXFLAGS="-Werror -Wno-unused-result -Wno-deprecated-declarations"
              ;;
          esac
          export CC="ccache $CC"
          export CXX="ccache $CXX"
          echo "::group::make distclean"
          make distclean || :
          echo "::endgroup::"
          echo "::group::autoreconf"
          autoreconf -vif
          echo "::endgroup::"
          echo "::group::configure"
          mkdir linux-${{ matrix.compiler.cc }}-${{ matrix.flags.name }}
          cd linux-${{ matrix.compiler.cc }}-${{ matrix.flags.name }}
          echo ">> Configure with $CC, $CXX, and ${{ matrix.flags.flags }}"
          ../configure --without-opt --with-experimental --enable-maintainer-mode ${{ matrix.flags.flags }} || { cat config.log; exit 1; }
          echo "::endgroup::"
          echo "::group::build"
          echo ">> Build using ${CPUS} jobs"
          make -j ${CPUS}
          echo "::endgroup::"
          echo "::group::run tests"
          make -j ${CPUS} check || { find . -name 'test-suite.log' -exec cat {} ';' && exit 1; }
          echo "::endgroup::"
          cd ..

      - name: Ccache stats after builds
        run: |
          ccache -s

      - name: Archive artifacts
        if: ${{ env.ACT != 'true' }}
        uses: actions/upload-artifact@v2
        with:
          name: linux-${{ matrix.compiler.cc }}-${{ matrix.flags.name }}
          path: |
            linux-${{ matrix.compiler.cc }}-${{ matrix.flags.name }}
            !linux-${{ matrix.compiler.cc }}-${{ matrix.flags.name }}/**/.deps
            !linux-${{ matrix.compiler.cc }}-${{ matrix.flags.name }}/**/.dirstamp
            !linux-${{ matrix.compiler.cc }}-${{ matrix.flags.name }}/**/*.a
            !linux-${{ matrix.compiler.cc }}-${{ matrix.flags.name }}/**/*.la
            !linux-${{ matrix.compiler.cc }}-${{ matrix.flags.name }}/**/*.lai
            !linux-${{ matrix.compiler.cc }}-${{ matrix.flags.name }}/**/*.o
            !linux-${{ matrix.compiler.cc }}-${{ matrix.flags.name }}/**/*.lo

  ubuntu_20_04:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        # gcc: 9.3.0, 10.2.0
        # clang: 10.0.0, 11.0.0, 12.0.1
        compiler:
          - cc:  gcc-10
            cxx: g++-10
          - cc:  gcc-9
            cxx: g++-9
          - cc:  clang-12
            cxx: clang++-12
          - cc:  clang-11
            cxx: clang++-11
          - cc:  clang-10
            cxx: clang++-10
        flags:
          - name: Gcrypt
            flags: "--with-gcrypt"
          - name: OpenSSL
            flags: ""

    name: Ubuntu 20.04 ${{ matrix.compiler.cc }} using ${{ matrix.flags.name }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 750
          submodules: 'recursive'

      - uses: actions/cache@v2
        id: cache
        if: ${{ env.ACT != 'true' }}
        with:
          path: |
            /home/runner/.ccache
          key: ${{ runner.os }}-${{ matrix.compiler.cc }}-${{ matrix.flags.name }}-${{ hashFiles('.github/workflows/linux.yml') }}
          restore-keys: ${{ runner.os }}-${{ matrix.compiler.cc }}-${{ matrix.flags.name }}

      - name: Install dependencies
        run: |
          sudo apt update -q
          sudo apt-get install -y autoconf automake build-essential ccache ethtool expect hostapd iw lcov libcmocka-dev libgcrypt20-dev libhwloc-dev libnl-3-dev libnl-genl-3-dev libpcap-dev libpcre2-dev libsqlite3-dev libssl-dev libtool pkg-config rfkill screen shtool tcpdump usbutils wpasupplicant zlib1g-dev

      - name: Ccache stats before builds
        run: |
          ccache -s

      - name: Build with ${{ matrix.compiler.cc }} using ${{ matrix.flags.name }}
        env:
          AM_COLOR_TESTS: always
        run: |
          CPUS=$(nproc)
          export CC="ccache ${{ matrix.compiler.cc }}"
          export CXX="ccache ${{ matrix.compiler.cxx }}"
          echo "::group::make distclean"
          make distclean || :
          echo "::endgroup::"
          echo "::group::autoreconf"
          autoreconf -vif
          echo "::endgroup::"
          echo "::group::configure"
          mkdir linux-${{ matrix.compiler.cc }}-${{ matrix.flags.name }}
          cd linux-${{ matrix.compiler.cc }}-${{ matrix.flags.name }}
          echo ">> Configure with $CC, $CXX, and ${{ matrix.flags.flags }}"
          ../configure --without-opt --with-experimental --enable-maintainer-mode ${{ matrix.flags.flags }} || { cat config.log; exit 1; }
          echo "::endgroup::"
          echo "::group::build"
          echo ">> Build using ${CPUS} jobs"
          make -j ${CPUS}
          echo "::endgroup::"
          echo "::group::run tests"
          make -j ${CPUS} check || { find . -name 'test-suite.log' -exec cat {} ';' && exit 1; }
          echo "::endgroup::"
          cd ..

      - name: Ccache stats after builds
        run: |
          ccache -s

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        if: ${{ env.ACT != 'true' }}
        with:
          name: linux-${{ matrix.compiler.cc }}-${{ matrix.flags.name }}
          path: |
            linux-${{ matrix.compiler.cc }}-${{ matrix.flags.name }}
            !linux-${{ matrix.compiler.cc }}-${{ matrix.flags.name }}/**/.deps
            !linux-${{ matrix.compiler.cc }}-${{ matrix.flags.name }}/**/.dirstamp
            !linux-${{ matrix.compiler.cc }}-${{ matrix.flags.name }}/**/*.a
            !linux-${{ matrix.compiler.cc }}-${{ matrix.flags.name }}/**/*.la
            !linux-${{ matrix.compiler.cc }}-${{ matrix.flags.name }}/**/*.lai
            !linux-${{ matrix.compiler.cc }}-${{ matrix.flags.name }}/**/*.o
            !linux-${{ matrix.compiler.cc }}-${{ matrix.flags.name }}/**/*.lo
